services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: farm_to_feed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: farm_to_feed
    depends_on:
      - db

volumes:
  postgres_data:
